FROM ubuntu
COPY smi3.cpp ./
COPY smi3c.cpp ./
RUN chmod ugo+x smi3.cpp
RUN chmod ugo+x smi3c.cpp
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y gcc-multilib
RUN apt-get install -y g++-multilib
