FROM ubuntu
COPY smi7_tcp_client.cpp ./
COPY smi7_tcp_server.cpp ./
COPY smi7_udp_client.cpp ./
COPY smi7_udp_server.cpp ./
RUN chmod ugo+x smi7_tcp_client.cpp
RUN chmod ugo+x smi7_tcp_server.cpp
RUN chmod ugo+x smi7_udp_client.cpp
RUN chmod ugo+x smi7_udp_server.cpp
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y g++-multilib
